hosts:
    mises:
        age:
            publickey: ENC[AES256_GCM,data:vMOFvTcy4gd2AcoQuwHCr/kUD7WbFQC2IBAkmlDK18DZtDPlDenvIcOwGztF7h5XviRO7jOSg5n1Xtas01g=,iv:IFmpZlvSk1ZWlsBEsnv+7OBWuFqyWzcFrsqXcKRDJrQ=,tag:VlWsRjFceS29CCySYbww5w==,type:str]
            privatekey: ENC[AES256_GCM,data:JpLbzJb93GOEwAjC9ZCMSZJLJrhsBTDPhzwG+8IolI9Y2lJwEmuvKqF6NTt049MT8GJVTz2XJBWWHoQrSL2j5oQRN+WTRBjpjiA=,iv:VjpiOYTj3j1Q72A3xIi9ut7mHS1Nuru+gWkvC39cCwg=,tag:hUqoR4uxnJVD0C2zOrl9XQ==,type:str]
    router:
        age:
            publicKey: ENC[AES256_GCM,data:MXojnm5+uE3oRIN13+v4mSHE57+8QLcMlzCqpRCmSpI1/CxUB11Ocd2t+Et/4BufIvCoYXh1YhBD6EOz3aE=,iv:xo0xntJvlLDscwHXg619BB8y7jnctnu7w5c1mAyRVaA=,tag:FvqlVOyaqMklwK2TvO6tlw==,type:str]
            privateKey: ENC[AES256_GCM,data:6qCU/q2KfoJkceFTQgAPSFDkNj0PW3It5cAHsvPXWpAvP0ScMsvpYTiLXEd/ObKYuqAfF5Jck/nDoBeFeFQwis70zJGze5EdM6mui9eUpWj2ZfzZu3ib4byvcAucdEegKSUfUIQ0cykISXl5gIwf/bus6jPWMlesY5fzwbkED9BRtAC8iZen9rfx/A0/39jCLOYKgwhQDmlXLYIjZwG7ZNjWEHfiEmRWdMgtDNoEOECBs8vVdnEVrZ3jDT4=,iv:M+1QGZZEvyccdnPJeeBlWsfeGvDIeQi16BWFQUzd+ys=,tag:TZ3ZmSz5sER2hX7JepZPsA==,type:str]
    nas1:
        age:
            publicKey: ENC[AES256_GCM,data:RX12bNJo+xMvuK0STOketKvM8SVRR/Cdgt+JZJS1jqzTuLL//kzpr8KqdN4OdKwHHQ/dEwoEkTDUrSmIYtg=,iv:xaAIHz5eRwegZK2B0VkWxprRenIZth+P81iyiARp1HY=,tag:oFUl4xt8cEg2RzQqae+zlw==,type:str]
            privateKey: ENC[AES256_GCM,data:YxKJS5MVSjFCVTysYqkJ4FEKCRRg1+HWt4iiGCj8ECfVQ3r7Cu15+dKtmQfmETV6vibUKcsmvN7K86bNKjsQIScoGe7udLrr5A5q/2UWTRlfDYvrVc3NcTzR14+L8Jc/pWxzp/DpR9xUGGcmqjibdnX1SRhgONuOqr1sbVPb4G+XFsfWxYqtwCUE6qtfTcJv0hQrvJ4eATBUye7q9onVcW8zHOWgbaOGaw4XZKRqMAvbMY340NXXR04Q1K4=,iv:J6JDjaykzGvAcVfHaXY1i5S6DYJuC3CYgfRFowGtUHY=,tag:NESUihn3qVvTr7kAshtUvQ==,type:str]
sops:
    age:
        - recipient: age1yubikey1qtefvr2wmwmxclr99t27vglfqhv4avp33dexfjg9290z4w458rpvys2ym74
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHV2RzRuZyBBN29raFhZ
            S1VvbkYzSk82UVUzQVF5UmJURzVvYXJobTBLTkpkUFMvWjVLZAovUWR0ZjM1L1F4
            ZVVzNnMzZVdWSEVHVFVjWUVocUlwWTlJM05CNXFONnBvCi0tLSBESURZWHJicXdQ
            RlVCc3h5S2xtSFlnbW8rbXZsR05ZRkdyUHllNDVzZUFrCuIrWo4vnSGDLPvmlbyn
            aK/a+LUVgcQOw2VcpAk2tSOZ552Zh7Rc1Ag8n8devygki9N6bqvd+h2JFTdfNGdJ
            IaA=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q2mpn0sh3636s7ajrhc7aanqava7h475544cyndnp4372u5vnk7gs692vk7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFqZHdWUSBBd0xET0xk
            WGV3UHk1Q3EwcjNhRFpNeENnWjUycW9ZRTdaZERXaXd2ZWNnbgovektRYXZtTCtY
            S0NpaVBucTQxcDVGQWRTVDVnQ2lGeE10bUhNVjNMR3M0Ci0tLSBjYytubWx2Ukdw
            Zm9ybVk1bk5welN1ejlMMmk4OTNHVzI4bFovZ2pxOVk0CmTcZcV1Yoxedr0J7bgM
            rrI2e1SZn1kmEhkTi3Ld577s6rCGeS8HHU+CyHYaIVEU+mLInD4e58V9s/XxF0J7
            ujI=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-13T01:34:20Z"
    mac: ENC[AES256_GCM,data:EmU6lP0f7yrROy42qMr4xM6mGGgNHJ3Cd4OKFLISsryCPfJ19kkS62iT7kPnu1x+I7XeyJI0KLPIa/ZM+WIfzHZKkGKviJwVZOcdSBnubZZKmj6nWREHWUtEHYqZSRdlnh1yi9Xj33tvwDBGMgoFLTza8dcV+Nwyf1HW6hm36JE=,iv:hWhMf+b2s/3YE5TRqLvvkyEYcWcq8094Fd8TY1+IyBs=,tag:6+dZs++2eJZpNT2g/jx2Rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
